### ISSUE TITLE
Most middleman-presentation commands don't work

### ISSUE THREAD

**Issue by ur5us** [fedux-org/middleman-presentation#1]
I'm using OSX 10.10, Ruby MRI 2.1.5, NodeJS 0.12.0 & Bower 1.3.12. After initializing the presentation with 

```ruby
middleman-presentation create presentation --title "my title" --speaker "Me"
```

and then running 

```ruby
bundle exec middleman-presentation create slide 01 02 03
```

I get 
> No value provided for required options '--title'
When I actually add the title option it generates a new presentation instead.

**Comment by maxmeyer** [comment]
Which version are you using? 

Can you please try the rc2?

```
gem install middleman-presentation -v 0.16.0.rc2
```

**Comment by maxmeyer** [comment]
New gem released. Please test again and re-open this issue if the problem occures again.
