### ISSUE TITLE
Middleman won't boot with new generated presentation

### ISSUE THREAD

**Issue by ur5us** [fedux-org/middleman-presentation#2]
```
"Sass::SyntaxError: File to import not found or unreadable: reveal.js/css/reveal.min.
Load paths:  
/Users/ur5us/dev/presentations/demo/source/stylesheets  
/Users/ur5us/.rvm/gems/ruby-2.1.5/gems/compass-core-1.0.3/stylesheets  
Compass::SpriteImporter  (in /Users/ur5us/dev/presentations/demo/source/stylesheets/application.scss:1)"
```

Without running the build step for reveal.js the file `reveal.min.css` won't exist so the asset pipeline fails to compile the application manifest.

**Comment by maxmeyer** [comment]
Please use the `rc2` of 0.16.0. This should fix the problem. Can you give me feedback if your problem is fixed with the new release?

**Comment by maxmeyer** [comment]
New gem release. Please test again and re-open this issue if the problem occures again.
