### ISSUE TITLE
Can not use reveal.js themes

### ISSUE THREAD

**Issue by gap** [fedux-org/middleman-presentation#3]
There are several themes in vendor/assets/components/reveal.js/css/theme
 I can not figure out how to use any of them.  I've spent a couple hours working on this.   Let me know if there is a better place to ask questions.

**Comment by dg-ratiodata** [comment]
>  Let me know if there is a better place to ask 

For now  I will use the issue tracker of github for this. :smile: I'm not an active user of stackoverflow.

> There are several themes in vendor/assets/components/reveal.js/css/theme.  can not figure out how to use any of them

I'm not sure what you expect. I included an `application.scss` which imports the styles of the original `reveal.js`-themes. A good starting place for this is

```scss
@import 'normalize.css/normalize';
@import 'highlightjs/styles/zenburn';
@import 'reveal.js/css/reveal';
@import 'reveal.js/css/theme/template/mixins';
@import 'reveal.js/css/theme/template/settings';
// theme start
@import 'reveal.js/css/theme/league';
// theme end
@import 'middleman-presentation-helpers/footer/footer';
@import 'middleman-presentation-helpers/image_gallery/image_gallery';
@import 'middleman-presentation-helpers/images/images';
```
You may need to adjust the predefined slide in `source/slides/` to match the styles in the theme. If you want to use the original theme regularly, create your own "theme" - look [here](https://github.com/fedux-org/middleman-presentation-theme-common) and [here](https://github.com/fedux-org/middleman-presentation-theme-default) for some examples and make sure you read the section about themes in the [readme](https://github.com/fedux-org/middleman-presentation#creating-themes).

Btw:
You will see a lot of bullet points if you chose the "original"-theme with the default slide templates. To make them disappear use the apprioate css-style. I use `<ul>` and the like a lot with `display: flex` to arange things on my slides - see this [article](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) for more information about flexbox.

Does this answer your question?

Cheers
/dg

**Comment by gap** [comment]
Thanks Dg,

You wrote an excellent response .  It pointed me in the right direction.  I wasn't sure I should edit application.scss

> I'm not sure what you expect

I expected the background color to change.  My first problem was I assumed blood would turn the background to a shade of red, rather than use white =(  League fixed this, but I had to add it to the end, otherwise it was overwritten by another rule.  My final application.scss looks like:

```scss
@import 'normalize.css/normalize';
@import 'highlightjs/styles/zenburn';
@import 'reveal.js/css/reveal';
@import 'reveal.js/css/theme/template/mixins';
@import 'reveal.js/css/theme/template/settings';

@import 'middleman-presentation-helpers/footer/footer';
@import 'middleman-presentation-helpers/image_gallery/image_gallery';
@import 'middleman-presentation-helpers/images/images';
@import 'middleman-presentation-theme-default/stylesheets/middleman-presentation-theme-default';

// theme start
@import 'reveal.js/css/theme/night';
// theme end
```

BTW, I'm really enjoying middleman-presentation!

**Comment by dg-ratiodata** [comment]
Thanks a lot!

> BTW, I'm really enjoying middleman-presentation!

Then spread the word! :smile:

**Comment by dg-ratiodata** [comment]
If you mention me, please use my private account name ;-) @maxmeyer Thx.

**Comment by dg-ratiodata** [comment]
It's a private project I also use at work.
